### ISSUE TITLE
Wrong attribute name in css

### ISSUE THREAD

**Issue by xrotwang** [fmatter/pylingdocs#6]
Here
https://github.com/fmatter/pylingdocs/blob/53e418dc123c2489c36e57e19c4e8ef7b0c77b5d/src/pylingdocs/data/web/examples.css#L18
it should be `attr(id)` instead of `attr(value)`.

**Comment by fmatter** [comment]
`value` is set by [`number_examples`](https://github.com/fmatter/pylingdocs/blob/53e418dc123c2489c36e57e19c4e8ef7b0c77b5d/src/pylingdocs/data/web/examples.js#L6); the issue was that that method was not being executed in the HTML output.
